# Stage 1: builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .

# .env.production is generated by deploy.sh from .env.local just before build.
# Next.js automatically loads it — NEXT_PUBLIC_ vars get inlined into the
# client JS bundle at this stage with the real Firebase values.
# Server-only secrets (FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY) are
# injected at runtime by Cloud Run from Secret Manager.
ENV FIREBASE_CLIENT_EMAIL=build-placeholder
ENV FIREBASE_PRIVATE_KEY=build-placeholder

RUN npm run build

# Stage 2: runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 8080

CMD ["node", "server.js"]
